2025-04-01 15:09:44,057 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-04-01 15:09:44,195 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:09:44,348 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:09:44,373 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-04-01 15:15:21,878 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-04-01 15:15:21,997 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:15:22,140 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:15:22,772 - kedro.framework.session.session - INFO - Kedro project official-misconcept-lm-plan-gen-D34B
2025-04-01 15:15:25,919 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.language_model_planning_evaluation' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/pipeline.py", line 7, in <module>
    from .nodes import evaluate_language_model_planning
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/nodes.py", line 18, in <module>
    from better_language_model_for_plan_generation.utils.zero_to_fp32 import load_state_dict_from_zero_checkpoint
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/utils/zero_to_fp32.py", line 26, in <module>
    from deepspeed.utils import logger
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-01 15:15:25,941 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.further_ppo_training' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/pipeline.py", line 7, in <module>
    from .nodes import ppo_training
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/nodes.py", line 8, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-01 15:15:25,955 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:15:26,097 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-04-01 15:15:26,703 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2025-04-01 15:15:26,705 - kedro.io.data_catalog - INFO - Loading data from params:text_prompt_generation_params (MemoryDataset)...
2025-04-01 15:15:26,713 - kedro.pipeline.node - INFO - Running node: construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None
2025-04-01 15:15:26,848 - kedro.pipeline.node - ERROR - Node construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None failed with error: 
[Errno 2] No such file or directory: '/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/data/01_raw/LLMs-Planning/plan-bench/instances/barman/generated_domain.pddl'
2025-04-01 15:15:26,858 - kedro.runner.sequential_runner - WARNING - No nodes ran. Repeat the previous command to attempt a new run.
2025-04-01 15:39:49,543 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-04-01 15:39:49,660 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:39:49,803 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:39:49,912 - kedro.framework.session.session - INFO - Kedro project official-misconcept-lm-plan-gen-D34B
2025-04-01 15:39:52,892 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.language_model_planning_evaluation' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/pipeline.py", line 7, in <module>
    from .nodes import evaluate_language_model_planning
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/nodes.py", line 18, in <module>
    from better_language_model_for_plan_generation.utils.zero_to_fp32 import load_state_dict_from_zero_checkpoint
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/utils/zero_to_fp32.py", line 26, in <module>
    from deepspeed.utils import logger
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-01 15:39:52,905 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.further_ppo_training' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/pipeline.py", line 7, in <module>
    from .nodes import ppo_training
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/nodes.py", line 8, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-01 15:39:52,921 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-01 15:39:53,069 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-04-01 15:39:53,679 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2025-04-01 15:39:53,683 - kedro.io.data_catalog - INFO - Loading data from params:text_prompt_generation_params (MemoryDataset)...
2025-04-01 15:39:53,705 - kedro.pipeline.node - INFO - Running node: construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None
2025-04-01 15:39:53,840 - kedro.pipeline.node - ERROR - Node construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None failed with error: 
[Errno 2] No such file or directory: '/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/data/01_raw/LLMs-Planning/plan-bench/instances/barman/generated_domain.pddl'
2025-04-01 15:39:53,849 - kedro.runner.sequential_runner - WARNING - No nodes ran. Repeat the previous command to attempt a new run.
2025-04-02 11:08:05,748 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-04-02 11:08:05,943 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-02 11:08:06,113 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-02 11:08:06,198 - kedro.framework.session.session - INFO - Kedro project official-misconcept-lm-plan-gen-D34B
2025-04-02 11:08:10,309 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.language_model_planning_evaluation' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/pipeline.py", line 7, in <module>
    from .nodes import evaluate_language_model_planning
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/nodes.py", line 18, in <module>
    from better_language_model_for_plan_generation.utils.zero_to_fp32 import load_state_dict_from_zero_checkpoint
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/utils/zero_to_fp32.py", line 26, in <module>
    from deepspeed.utils import logger
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-02 11:08:10,323 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.further_ppo_training' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/pipeline.py", line 7, in <module>
    from .nodes import ppo_training
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/nodes.py", line 8, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-02 11:08:10,338 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-02 11:08:10,478 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-04-02 11:08:11,115 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2025-04-02 11:08:11,117 - kedro.io.data_catalog - INFO - Loading data from params:text_prompt_generation_params (MemoryDataset)...
2025-04-02 11:08:11,125 - kedro.pipeline.node - INFO - Running node: construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None
2025-04-02 11:08:11,254 - kedro.pipeline.node - ERROR - Node construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None failed with error: 
[Errno 2] No such file or directory: '/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/data/01_raw/LLMs-Planning/plan-bench/instances/barman/generated_domain.pddl'
2025-04-02 11:08:11,263 - kedro.runner.sequential_runner - WARNING - No nodes ran. Repeat the previous command to attempt a new run.
2025-04-02 11:10:45,119 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-04-02 11:10:45,229 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-02 11:10:45,362 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-02 11:10:45,440 - kedro.framework.session.session - INFO - Kedro project official-misconcept-lm-plan-gen-D34B
2025-04-02 11:10:48,254 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.language_model_planning_evaluation' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/pipeline.py", line 7, in <module>
    from .nodes import evaluate_language_model_planning
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/language_model_planning_evaluation/nodes.py", line 18, in <module>
    from better_language_model_for_plan_generation.utils.zero_to_fp32 import load_state_dict_from_zero_checkpoint
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/utils/zero_to_fp32.py", line 26, in <module>
    from deepspeed.utils import logger
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-02 11:10:48,265 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py:450: UserWarning: An error occurred while importing the 'better_language_model_for_plan_generation.pipelines.further_ppo_training' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 442, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/__init__.py", line 6, in <module>
    from .pipeline import create_pipeline
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/pipeline.py", line 7, in <module>
    from .nodes import ppo_training
  File "/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/src/better_language_model_for_plan_generation/pipelines/further_ppo_training/nodes.py", line 8, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'

  warnings.warn(

2025-04-02 11:10:48,280 - py.warnings - WARNING - /home/macsilva/anaconda3/envs/learning_to_plan/lib/python3.11/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-04-02 11:10:48,417 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-04-02 11:10:49,054 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2025-04-02 11:10:49,056 - kedro.io.data_catalog - INFO - Loading data from params:text_prompt_generation_params (MemoryDataset)...
2025-04-02 11:10:49,065 - kedro.pipeline.node - INFO - Running node: construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None
2025-04-02 11:50:10,596 - kedro.pipeline.node - ERROR - Node construct_huggingface_dataset_node: construct_huggingface_dataset([params:text_prompt_generation_params]) -> None failed with error: 
[Errno 2] No such file or directory: '/home/macsilva/Desktop/learning_to_plan/official-misconcept-lm-plan-gen-D34B/data/03_primary/llm_plan_generation_dataset_qwen/t0/train/chunk_0.jsonl'
2025-04-02 11:50:10,607 - kedro.runner.sequential_runner - WARNING - No nodes ran. Repeat the previous command to attempt a new run.
